# Clase pandas

In [8]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

2.4.6
3.0.3

In [9]:
capacity = pd.Series([20, 15, 25, 30], index=["Xativa", "Colon", "Ruzafa", "Angel Gimera"])
print(capacity)

Xativa          20
Colon           15
Ruzafa          25
Angel Gimera    30
dtype: int64

In [10]:
print(capacity * 0.5)

Xativa          10.0
Colon            7.5
Ruzafa          12.5
Angel Gimera    15.0
dtype: float64

In [11]:
mini = pd.DataFrame({
    "Station": ["Xativa", "Colon", "Ruzafa", "Angel Gimera"],
    "Capacity": [20, 15, 25, 30],
    "Bikes": [12, 3, 18, 25]
})

print(mini)

        Station  Capacity  Bikes
0        Xativa        20     12
1         Colon        15      3
2        Ruzafa        25     18
3  Angel Gimera        30     25

In [12]:
print(mini.columns.to_list())
print(mini.dtypes)

['Station', 'Capacity', 'Bikes']
Station       str
Capacity    int64
Bikes       int64
dtype: object

In [14]:
mini["Ocupancy"] = (mini["Bikes"] / mini["Capacity"]).round(2)

mini["Status"] = np.where(mini["Ocupancy"] > 0.7, "High", "Okay")

print(mini)

        Station  Capacity  Bikes  Ocupancy Status
0        Xativa        20     12      0.60   Okay
1         Colon        15      3      0.20   Okay
2        Ruzafa        25     18      0.72   High
3  Angel Gimera        30     25      0.83   High

In [24]:
stations = pd.read_csv("./data/stations.csv")

stations.head()

,station_id,name,district,lat,lon,capacity,opened
0,1,"Calle Caballeros, 22",Ciutat Vella,39.475962,-0.383585,15.0,2014-01-07
1,2,"Calle San Vicente Mártir, 43",Ciutat Vella,39.473832,-0.377248,30.0,2012-03-02
2,3,"Calle Caballeros, 78",Ciutat Vella,39.474096,-0.373120,30.0,2019-04-14
3,4,"Plaza de la Reina, 76",Ciutat Vella,39.474658,-0.375356,25.0,2018-05-20
4,5,"Calle San Vicente Mártir, 54",Ciutat Vella,39.477193,-0.376522,20.0,2012-08-21

In [21]:
usage_hourly = pd.read_csv("./data/usage_hourly.csv")

usage_hourly.head()

   station_id            timestamp  rentals  returns  bikes_available
0          58  2026-09-25 22:00:00        0        0             20.0
1          24  2026-09-13 02:00:00        0        0             16.0
2          17  2026-09-04 03:00:00        0        0             15.0
3          36  2026-09-13 03:00:00        0        0             14.0
4          39  2026-09-20 11:00:00        0        4             18.0

In [27]:
stations.describe()

       station_id        lat        lon   capacity
count   60.000000  60.000000  60.000000  58.000000
mean    30.500000  39.470015  -0.370467  23.448276
std     17.464249   0.010947   0.020668   6.435026
min      1.000000  39.446556  -0.411840  15.000000
25%     15.750000  39.463084  -0.388257  20.000000
50%     30.500000  39.468368  -0.372618  25.000000
75%     45.250000  39.476270  -0.356271  25.000000
max     60.000000  39.491789  -0.329369  35.000000

In [28]:
usage_hourly.describe()

         station_id       rentals       returns  bikes_available
count  43350.000000  43350.000000  43350.000000     42480.000000
mean      30.497416      1.885329      1.687843        12.050235
std       17.319319     16.740842      2.667507         6.983225
min        1.000000      0.000000     -1.000000         0.000000
25%       15.000000      0.000000      0.000000         8.000000
50%       30.000000      1.000000      1.000000        12.000000
75%       45.000000      2.000000      2.000000        16.000000
max       60.000000    999.000000     29.000000        35.000000

In [29]:
stations.isna()

    station_id   name  district    lat    lon  capacity  opened
0        False  False     False  False  False     False   False
1        False  False     False  False  False     False   False
2        False  False     False  False  False     False   False
3        False  False     False  False  False     False   False
4        False  False     False  False  False     False   False
5        False  False     False  False  False     False   False
6        False  False     False  False  False     False   False
7        False  False     False  False  False     False   False
8        False  False     False  False  False     False   False
9        False  False     False  False  False     False   False
10       False  False     False  False  False     False   False
11       False  False     False  False  False     False   False
12       False  False     False  False  False     False   False
13       False  False     False  False  False      True   False
14       False  False     False  False  False     False   False
15       False  False     False  False  False     False   False
16       False  False     False  False  False     False   False
17       False  False     False  False  False     False   False
18       False  False     False  False  False     False   False
19       False  False     False  False  False     False   False
20       False  False     False  False  False     False   False
21       False  False     False  False  False     False   False
22       False  False     False  False  False     False   False
23       False  False     False  False  False     False   False
24       False  False     False  False  False     False   False
25       False  False     False  False  False     False   False
26       False  False     False  False  False     False   False
27       False  False     False  False  False     False   False
28       False  False     False  False  False     False   False
29       False  False     False  False  False     False   False
30       False  False     False  False  False     False   False
31       False  False     False  False  False     False   False
32       False  False     False  False  False     False   False
33       False  False     False  False  False     False   False
34       False  False     False  False  False     False   False
35       False  False     False  False  False     False   False
36       False  False     False  False  False     False   False
37       False  False     False  False  False     False   False
38       False  False     False  False  False     False   False
39       False  False     False  False  False     False   False
40       False  False     False  False  False     False   False
41       False  False     False  False  False     False   False
42       False  False     False  False  False     False   False
43       False  False     False  False  False     False   False
44       False  False     False  False  False     False   False
45       False  False     False  False  False     False   False
46       False  False     False  False  False     False   False
47       False  False     False  False  False     False   False
48       False  False     False  False  False     False   False
49       False  False     False  False  False     False   False
50       False  False     False  False  False     False   False
51       False  False     False  False  False     False   False
52       False  False     False  False  False     False   False
53       False  False     False  False  False     False   False
54       False  False     False  False  False      True   False
55       False  False     False  False  False     False   False
56       False  False     False  False  False     False   False
57       False  False     False  False  False     False   False
58       False  False     False  False  False     False   False
59       False  False     False  False  False     False   False